import type { MenuItem } from '@/contexts/POSContext';

export const godswillMenuItems: MenuItem[] = [
  // BESTSELLER
  { id: 'best-1', sku: 'GW-BST-001', name: 'Biscoff Coffee', price: 180, costPrice: 65, category: 'BESTSELLER', description: 'Biscoff-infused coffee', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'bestseller'] },
  { id: 'best-2', sku: 'GW-BST-002', name: "S'mores Latte", price: 180, costPrice: 70, category: 'BESTSELLER', description: "S'mores flavored latte", unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'bestseller'] },
  { id: 'best-3', sku: 'GW-BST-003', name: 'Dirty Matcha', price: 180, costPrice: 72, category: 'BESTSELLER', description: 'Matcha with espresso shot', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha', 'bestseller'] },
  { id: 'best-4', sku: 'GW-BST-004', name: 'Golden Banana Latte', price: 220, costPrice: 85, category: 'BESTSELLER', description: 'Banana-infused latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'bestseller'] },
  { id: 'best-5', sku: 'GW-BST-005', name: 'White Mocha', price: 180, costPrice: 65, category: 'BESTSELLER', description: 'White chocolate mocha', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'bestseller'] },
  { id: 'best-6', sku: 'GW-BST-006', name: 'Seasalt Latte', price: 180, costPrice: 60, category: 'BESTSELLER', description: 'Sea salt topped latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'bestseller'] },
  { id: 'best-7', sku: 'GW-BST-007', name: 'Coffee Jelly', price: 220, costPrice: 80, category: 'BESTSELLER', description: 'Coffee with coffee jelly', unit: 'cup', isAvailable: true, tags: ['cold', 'bestseller'] },
  // CLASSIC COFFEE
  { id: 'cc-1', sku: 'GW-CCF-001', name: 'Spanish Latte', price: 150, costPrice: 55, category: 'CLASSIC COFFEE', description: 'Sweetened condensed milk latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-2', sku: 'GW-CCF-002', name: 'Caramel Macchiato', price: 160, costPrice: 60, category: 'CLASSIC COFFEE', description: 'Espresso with caramel', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-3', sku: 'GW-CCF-003', name: 'Salted Caramel', price: 160, costPrice: 60, category: 'CLASSIC COFFEE', description: 'Salted caramel coffee', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-4', sku: 'GW-CCF-004', name: 'Americano', price: 100, costPrice: 30, category: 'CLASSIC COFFEE', description: 'Classic americano', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-5', sku: 'GW-CCF-005', name: 'French Vanilla', price: 150, costPrice: 55, category: 'CLASSIC COFFEE', description: 'French vanilla latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-6', sku: 'GW-CCF-006', name: 'Thai Tea Latte', price: 150, costPrice: 50, category: 'CLASSIC COFFEE', description: 'Thai tea with milk', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-7', sku: 'GW-CCF-007', name: 'Cafe Latte', price: 130, costPrice: 45, category: 'CLASSIC COFFEE', description: 'Classic cafe latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold'] },
  { id: 'cc-8', sku: 'GW-CCF-008', name: 'Cappuccino', price: 130, costPrice: 45, category: 'CLASSIC COFFEE', description: 'Classic cappuccino', unit: 'cup', isAvailable: true, tags: ['hot'] },
  { id: 'cc-9', sku: 'GW-CCF-009', name: 'Oat Milk Latte', price: 160, costPrice: 65, category: 'CLASSIC COFFEE', description: 'Latte with oat milk', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'vegan'] },
  // MATCHA SERIES
  { id: 'mat-1', sku: 'GW-MAT-001', name: 'Strawberry Matcha', price: 180, costPrice: 70, category: 'MATCHA SERIES', description: 'Strawberry matcha latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha'] },
  { id: 'mat-2', sku: 'GW-MAT-002', name: 'Blueberry Matcha', price: 180, costPrice: 70, category: 'MATCHA SERIES', description: 'Blueberry matcha latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha'] },
  { id: 'mat-3', sku: 'GW-MAT-003', name: 'Matcha Milk', price: 180, costPrice: 68, category: 'MATCHA SERIES', description: 'Classic matcha milk', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha'] },
  { id: 'mat-4', sku: 'GW-MAT-004', name: 'Ube Matcha', price: 180, costPrice: 72, category: 'MATCHA SERIES', description: 'Ube matcha latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha'] },
  { id: 'mat-5', sku: 'GW-MAT-005', name: 'Choco Matcha', price: 180, costPrice: 70, category: 'MATCHA SERIES', description: 'Chocolate matcha latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha'] },
  { id: 'mat-6', sku: 'GW-MAT-006', name: 'Seasalt Matcha', price: 180, costPrice: 68, category: 'MATCHA SERIES', description: 'Sea salt matcha latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'matcha'] },
  // MILK SERIES
  { id: 'milk-1', sku: 'GW-MLK-001', name: 'Strawberry Milk', price: 180, costPrice: 65, category: 'MILK SERIES', description: 'Strawberry flavored milk', unit: 'cup', isAvailable: true, tags: ['cold'] },
  { id: 'milk-2', sku: 'GW-MLK-002', name: 'Blueberry Milk', price: 180, costPrice: 65, category: 'MILK SERIES', description: 'Blueberry flavored milk', unit: 'cup', isAvailable: true, tags: ['cold'] },
  { id: 'milk-3', sku: 'GW-MLK-003', name: 'Oreo Latte', price: 180, costPrice: 68, category: 'MILK SERIES', description: 'Oreo cookies latte', unit: 'cup', isAvailable: true, tags: ['cold'] },
  { id: 'milk-4', sku: 'GW-MLK-004', name: 'Mango Milk', price: 180, costPrice: 65, category: 'MILK SERIES', description: 'Mango flavored milk', unit: 'cup', isAvailable: true, tags: ['cold'] },
  { id: 'milk-5', sku: 'GW-MLK-005', name: 'Choco Milk', price: 180, costPrice: 60, category: 'MILK SERIES', description: 'Chocolate milk', unit: 'cup', isAvailable: true, tags: ['cold'] },
  { id: 'milk-6', sku: 'GW-MLK-006', name: 'Ube Milk', price: 180, costPrice: 65, category: 'MILK SERIES', description: 'Ube flavored milk', unit: 'cup', isAvailable: true, tags: ['cold'] },
  { id: 'milk-7', sku: 'GW-MLK-007', name: 'Choco Strawberry', price: 180, costPrice: 68, category: 'MILK SERIES', description: 'Choco strawberry milk', unit: 'cup', isAvailable: true, tags: ['cold'] },
  // FRAPPE
  { id: 'frp-1', sku: 'GW-FRP-001', name: 'Javachip Frappe', price: 200, costPrice: 80, category: 'FRAPPE', description: 'Java chip blended frappe', unit: 'cup', isAvailable: true, tags: ['cold', 'blended'] },
  { id: 'frp-2', sku: 'GW-FRP-002', name: 'Caramel Frappe', price: 200, costPrice: 78, category: 'FRAPPE', description: 'Caramel blended frappe', unit: 'cup', isAvailable: true, tags: ['cold', 'blended'] },
  { id: 'frp-3', sku: 'GW-FRP-003', name: 'Matcha Frappe', price: 220, costPrice: 88, category: 'FRAPPE', description: 'Matcha blended frappe', unit: 'cup', isAvailable: true, tags: ['cold', 'blended', 'matcha'] },
  { id: 'frp-4', sku: 'GW-FRP-004', name: 'Biscoff Latte Frappe', price: 220, costPrice: 90, category: 'FRAPPE', description: 'Biscoff latte frappe', unit: 'cup', isAvailable: true, tags: ['cold', 'blended'] },
  // TIRAMISU SERIES
  { id: 'tir-1', sku: 'GW-TIR-001', name: 'Tiramisu Latte', price: 270, costPrice: 110, category: 'TIRAMISU SERIES', description: 'Classic tiramisu latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'premium'] },
  { id: 'tir-2', sku: 'GW-TIR-002', name: 'Biscoff Tiramisu', price: 270, costPrice: 115, category: 'TIRAMISU SERIES', description: 'Biscoff tiramisu latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'premium'] },
  { id: 'tir-3', sku: 'GW-TIR-003', name: 'Matcha Tiramisu', price: 270, costPrice: 115, category: 'TIRAMISU SERIES', description: 'Matcha tiramisu latte', unit: 'cup', isAvailable: true, tags: ['hot', 'cold', 'premium', 'matcha'] },
  // SNACKS
  { id: 'snk-1', sku: 'GW-SNK-001', name: 'Shawarma', price: 59, costPrice: 22, category: 'SNACKS', description: 'Classic shawarma wrap', unit: 'piece', isAvailable: true, tags: ['savory'] },
  { id: 'snk-2', sku: 'GW-SNK-002', name: 'Nachos', price: 170, costPrice: 65, category: 'SNACKS', description: 'Loaded nachos', unit: 'serving', isAvailable: true, tags: ['savory', 'shareable'] },
  { id: 'snk-3', sku: 'GW-SNK-003', name: 'Shawarma Salad', price: 150, costPrice: 55, category: 'SNACKS', description: 'Fresh shawarma salad', unit: 'serving', isAvailable: true, tags: ['savory'] },
  { id: 'snk-4', sku: 'GW-SNK-004', name: 'Shawarma Rice', price: 130, costPrice: 48, category: 'SNACKS', description: 'Shawarma with rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice'] },
  { id: 'snk-5', sku: 'GW-SNK-005', name: 'Hungarian Sausage Sandwich', price: 130, costPrice: 50, category: 'SNACKS', description: 'Hungarian sausage on bread', unit: 'piece', isAvailable: true, tags: ['savory'] },
  { id: 'snk-6', sku: 'GW-SNK-006', name: 'Drip Chicken and Fries', price: 250, costPrice: 100, category: 'SNACKS', description: 'Fried chicken with fries', unit: 'serving', isAvailable: true, tags: ['savory', 'chicken'] },
  { id: 'snk-7', sku: 'GW-SNK-007', name: 'Pasta - Spaghetti', price: 170, costPrice: 60, category: 'SNACKS', description: 'Classic spaghetti', unit: 'serving', isAvailable: true, tags: ['savory', 'pasta'] },
  { id: 'snk-8', sku: 'GW-SNK-008', name: 'Pasta - Carbonara', price: 180, costPrice: 65, category: 'SNACKS', description: 'Creamy carbonara', unit: 'serving', isAvailable: true, tags: ['savory', 'pasta'] },
  { id: 'snk-9', sku: 'GW-SNK-009', name: 'Pasta - Truffle', price: 200, costPrice: 75, category: 'SNACKS', description: 'Truffle pasta', unit: 'serving', isAvailable: true, tags: ['savory', 'pasta', 'premium'] },
  { id: 'snk-10', sku: 'GW-SNK-010', name: 'Onion Rings', price: 160, costPrice: 55, category: 'SNACKS', description: 'Crispy onion rings', unit: 'serving', isAvailable: true, tags: ['savory', 'fried'] },
  { id: 'snk-11', sku: 'GW-SNK-011', name: 'Cheesy Fries', price: 150, costPrice: 50, category: 'SNACKS', description: 'Fries with melted cheese', unit: 'serving', isAvailable: true, tags: ['savory', 'fried'] },
  { id: 'snk-12', sku: 'GW-SNK-012', name: 'Cheese Sticks', price: 170, costPrice: 60, category: 'SNACKS', description: 'Golden cheese sticks', unit: 'serving', isAvailable: true, tags: ['savory', 'fried'] },
  { id: 'snk-13', sku: 'GW-SNK-013', name: 'Pica-Pica Platter', price: 270, costPrice: 110, category: 'SNACKS', description: 'Fries, nachos, chicken popcorn', unit: 'serving', isAvailable: true, tags: ['savory', 'shareable'] },
  { id: 'snk-14', sku: 'GW-SNK-014', name: 'Chicken Wings (4pcs)', price: 200, costPrice: 80, category: 'SNACKS', description: '4 pieces chicken wings', unit: 'serving', isAvailable: true, tags: ['savory', 'chicken'] },
  { id: 'snk-15', sku: 'GW-SNK-015', name: 'Chicken Wings (6pcs)', price: 290, costPrice: 115, category: 'SNACKS', description: '6 pieces chicken wings', unit: 'serving', isAvailable: true, tags: ['savory', 'chicken'] },
  { id: 'snk-16', sku: 'GW-SNK-016', name: 'Chicken Wings (12pcs)', price: 550, costPrice: 220, category: 'SNACKS', description: '12 pieces chicken wings', unit: 'serving', isAvailable: true, tags: ['savory', 'chicken', 'shareable'] },
  // BREAD
  { id: 'brd-1', sku: 'GW-BRD-001', name: 'Clubhouse Sandwich with Fries', price: 160, costPrice: 62, category: 'BREAD', description: 'Clubhouse sandwich served with fries', unit: 'serving', isAvailable: true, tags: ['savory'] },
  { id: 'brd-2', sku: 'GW-BRD-002', name: 'Croffle - Blueberry', price: 140, costPrice: 50, category: 'BREAD', description: 'Blueberry croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry'] },
  { id: 'brd-3', sku: 'GW-BRD-003', name: 'Croffle - Mango', price: 140, costPrice: 50, category: 'BREAD', description: 'Mango croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry'] },
  { id: 'brd-4', sku: 'GW-BRD-004', name: 'Croffle - Biscoff Cream', price: 140, costPrice: 52, category: 'BREAD', description: 'Biscoff cream croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry'] },
  { id: 'brd-5', sku: 'GW-BRD-005', name: 'Croffle - Biscoff Crumble', price: 140, costPrice: 52, category: 'BREAD', description: 'Biscoff crumble croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry'] },
  { id: 'brd-6', sku: 'GW-BRD-006', name: 'Croffle - Cookies and Cream', price: 140, costPrice: 52, category: 'BREAD', description: 'Cookies and cream croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry'] },
  { id: 'brd-7', sku: 'GW-BRD-007', name: 'Croffle - Matcha', price: 140, costPrice: 52, category: 'BREAD', description: 'Matcha croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry', 'matcha'] },
  { id: 'brd-8', sku: 'GW-BRD-008', name: 'Croffle - Nutella Almond', price: 140, costPrice: 55, category: 'BREAD', description: 'Nutella almond croffle', unit: 'piece', isAvailable: true, tags: ['sweet', 'pastry'] },
  { id: 'brd-9', sku: 'GW-BRD-009', name: 'Donut - Chocolate', price: 80, costPrice: 28, category: 'BREAD', description: 'Chocolate donut', unit: 'piece', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-10', sku: 'GW-BRD-010', name: 'Donut - Butternut', price: 80, costPrice: 28, category: 'BREAD', description: 'Butternut donut', unit: 'piece', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-11', sku: 'GW-BRD-011', name: 'Donut - Bavarian', price: 80, costPrice: 30, category: 'BREAD', description: 'Bavarian donut', unit: 'piece', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-12', sku: 'GW-BRD-012', name: 'Cookie - Red Velvet (Piece)', price: 99, costPrice: 35, category: 'BREAD', description: 'Red velvet cookie per piece', unit: 'piece', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-13', sku: 'GW-BRD-013', name: 'Cookie - Red Velvet (Tub)', price: 160, costPrice: 55, category: 'BREAD', description: 'Red velvet cookie per tub', unit: 'box', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-14', sku: 'GW-BRD-014', name: 'Cookie - Choco Chip (Piece)', price: 99, costPrice: 35, category: 'BREAD', description: 'Choco chip cookie per piece', unit: 'piece', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-15', sku: 'GW-BRD-015', name: 'Cookie - Choco Chip (Tub)', price: 160, costPrice: 55, category: 'BREAD', description: 'Choco chip cookie per tub', unit: 'box', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-16', sku: 'GW-BRD-016', name: 'Cookie - Biscoff (Piece)', price: 99, costPrice: 35, category: 'BREAD', description: 'Biscoff cookie per piece', unit: 'piece', isAvailable: true, tags: ['sweet'] },
  { id: 'brd-17', sku: 'GW-BRD-017', name: 'Cookie - Biscoff (Tub)', price: 160, costPrice: 55, category: 'BREAD', description: 'Biscoff cookie per tub', unit: 'box', isAvailable: true, tags: ['sweet'] },
  // RICE MEALS
  { id: 'rice-1', sku: 'GW-RCM-001', name: 'Chicsilog', price: 160, costPrice: 65, category: 'RICE MEAL', description: 'Chicken sisig, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-2', sku: 'GW-RCM-002', name: 'Tapsilog', price: 180, costPrice: 72, category: 'RICE MEAL', description: 'Tapa, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-3', sku: 'GW-RCM-003', name: 'Spamsilog', price: 160, costPrice: 68, category: 'RICE MEAL', description: 'Spam, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-4', sku: 'GW-RCM-004', name: 'Sisigsilog', price: 180, costPrice: 72, category: 'RICE MEAL', description: 'Sisig, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-5', sku: 'GW-RCM-005', name: 'Baconsilog', price: 160, costPrice: 65, category: 'RICE MEAL', description: 'Bacon, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-6', sku: 'GW-RCM-006', name: 'Tocilog', price: 160, costPrice: 62, category: 'RICE MEAL', description: 'Tocino, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-7', sku: 'GW-RCM-007', name: 'Chicken Tonkatsu', price: 180, costPrice: 75, category: 'RICE MEAL', description: 'Breaded chicken cutlet with rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'chicken'] },
  { id: 'rice-8', sku: 'GW-RCM-008', name: 'Pork Tonkatsu', price: 180, costPrice: 75, category: 'RICE MEAL', description: 'Breaded pork cutlet with rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice'] },
  { id: 'rice-9', sku: 'GW-RCM-009', name: 'Liemposilog', price: 180, costPrice: 72, category: 'RICE MEAL', description: 'Liempo, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
  { id: 'rice-10', sku: 'GW-RCM-010', name: 'Hungariansilog', price: 180, costPrice: 72, category: 'RICE MEAL', description: 'Hungarian sausage, egg, rice', unit: 'serving', isAvailable: true, tags: ['savory', 'rice', 'silog'] },
];
